"use client";
import localFont from "next/font/local";
import "./globals.css";
import { LeftSidebar } from "./components/LeftSidebar";
import { RightSidebar } from "./components/RightSidebar";
import { Header } from "./components/Header";
import { useState } from "react";
import { Inter } from 'next/font/google'
// import { useRouter, usePathname, useSearchParams } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({ children }) {

  // const router = usePathname();
  const [isLeftSidebarOpen, setIsLeftSidebarOpen] = useState(true);
  const [isRightSidebarOpen, setIsRightSidebarOpen] = useState(false);
  // if(router != "/"){
  //   setIsRightSidebarOpen(!isRightSidebarOpen)
  // }

  const toggleLeftSidebar = () => setIsLeftSidebarOpen(!isLeftSidebarOpen);
  const toggleRightSidebar = () => setIsRightSidebarOpen(!isRightSidebarOpen);
  return (
    <html lang="en">
      <body className={`${inter.className} flex font-inter text-sm text-[#1C1C1C] dark:text-white dark:bg-blackTheme`}>
        {isLeftSidebarOpen && <LeftSidebar isOpen={isLeftSidebarOpen} />}
        <div className="flex flex-col flex-grow">
          <Header
            toggleLeftSidebar={toggleLeftSidebar}
            toggleRightSidebar={toggleRightSidebar}
          />
          {children}
        </div>
        {isRightSidebarOpen && <RightSidebar isOpen={isRightSidebarOpen} />}
      </body>
    </html>
  );
}
